// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.0.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowDemo
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("ReportFlyTip", Description="\tAs anyone\r\n\tI want to report a fly-tip\r\n\tso my way isn\'t blocked and the environ" +
        "ment is clean and tidy", SourceFile="ReportFlyTip.feature", SourceLine=0)]
    public partial class ReportFlyTipFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ReportFlyTip.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ReportFlyTip", "\tAs anyone\r\n\tI want to report a fly-tip\r\n\tso my way isn\'t blocked and the environ" +
                    "ment is clean and tidy", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Public Road", new string[] {
                "mytag1"}, SourceLine=6)]
        public virtual void ReportFlyTipPublicRoad()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Public Road", new string[] {
                        "mytag1"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.When("they select Yes to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.And("they click on the next button after selecting the problem source as public road", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.When("User enters the Fly tip location & clicks next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.And("They enter the relevant details on the public road information pages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.Then("they get a confirmation screen with the case number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Car park", new string[] {
                "mytag2"}, SourceLine=15)]
        public virtual void ReportFlyTipCarPark()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Car park", new string[] {
                        "mytag2"});
#line 16
this.ScenarioSetup(scenarioInfo);
#line 17
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 18
 testRunner.When("they select Yes to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.And("they click on the next button after selecting the problem source as Car Park", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.When("User selects the car park location & clicks next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.And("They enter the relevant details on the car park information pages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.Then("they get a confirmation screen with the case number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip In a park", new string[] {
                "mytag3"}, SourceLine=24)]
        public virtual void ReportFlyTipInAPark()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip In a park", new string[] {
                        "mytag3"});
#line 25
this.ScenarioSetup(scenarioInfo);
#line 26
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 27
 testRunner.When("they select Yes to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 28
 testRunner.And("they click on the next button after selecting the problem source as In a park", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("User enters the park details & clicks next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.And("They enter the relevant details on the park information pages", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.Then("they get a confirmation screen with the case number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip private land", new string[] {
                "mytag4"}, SourceLine=33)]
        public virtual void ReportFlyTipPrivateLand()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip private land", new string[] {
                        "mytag4"});
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 36
 testRunner.When("they select Yes to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.When("they click on the next button after selecting the problem source as private land", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then("they get a confirmation screen with the case number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Somewhere else", new string[] {
                "mytag4"}, SourceLine=40)]
        public virtual void ReportFlyTipSomewhereElse()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Somewhere else", new string[] {
                        "mytag4"});
#line 41
this.ScenarioSetup(scenarioInfo);
#line 42
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
 testRunner.When("they select Yes to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 44
 testRunner.When("they click on the next button after selecting the problem source as Somewhere Els" +
                    "e", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("they get a confirmation screen with the case number", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation inside 24 hrs", SourceLine=46)]
        public virtual void ReportFlyTipEscalationInside24Hrs()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation inside 24 hrs", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 48
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 49
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("they get a message on the screen that they can\'t escalate case as its inside 24 h" +
                    "rs", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation outside 24 hrs - Open with Veolia - Allocated to Neighbou" +
            "rhoods team", SourceLine=53)]
        public virtual void ReportFlyTipEscalationOutside24Hrs_OpenWithVeolia_AllocatedToNeighbourhoodsTeam()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation outside 24 hrs - Open with Veolia - Allocated to Neighbou" +
                    "rhoods team", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.And("they see a message on the screen that case is allocated to contractor & they can " +
                    "provide additional details to the case", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.When("they enter additional case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 61
 testRunner.Then("they get a confirmation case number & a corresponding email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation outside 24 hrs - Completed by Veolia hence new request", SourceLine=62)]
        public virtual void ReportFlyTipEscalationOutside24Hrs_CompletedByVeoliaHenceNewRequest()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation outside 24 hrs - Completed by Veolia hence new request", ((string[])(null)));
#line 63
this.ScenarioSetup(scenarioInfo);
#line 64
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 66
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.And("they see a message on the screen that case is completed by contractor & they can " +
                    "provide additional details to reopen the case", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.When("they enter additional case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 70
 testRunner.Then("they get a confirmation case number & a corresponding email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation outside 24 hrs - Veolia needs more information", SourceLine=71)]
        public virtual void ReportFlyTipEscalationOutside24Hrs_VeoliaNeedsMoreInformation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation outside 24 hrs - Veolia needs more information", ((string[])(null)));
#line 72
this.ScenarioSetup(scenarioInfo);
#line 73
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 74
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 75
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 77
 testRunner.And("they see a message on the screen that contractor needs additional details & they " +
                    "can provide details to the case", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
 testRunner.When("they enter additional case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.Then("they get a confirmation case number & a corresponding email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation outside 24 hrs - Not completed by Veolia - Allocated to N" +
            "eighbourhoods team", SourceLine=80)]
        public virtual void ReportFlyTipEscalationOutside24Hrs_NotCompletedByVeolia_AllocatedToNeighbourhoodsTeam()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation outside 24 hrs - Not completed by Veolia - Allocated to N" +
                    "eighbourhoods team", ((string[])(null)));
#line 81
this.ScenarioSetup(scenarioInfo);
#line 82
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 84
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.And("they see a message on the screen that Not Completed by Veolia for “Too Big /  Pri" +
                    "vate Property/Land /Health &amp; Safety Issue” & they can provide additional det" +
                    "ails to the case", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.When("they enter additional case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 88
 testRunner.Then("they get a confirmation case number & a corresponding email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("ReportFlyTip Escalation outside 24 hrs - ID Verde", SourceLine=89)]
        public virtual void ReportFlyTipEscalationOutside24Hrs_IDVerde()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("ReportFlyTip Escalation outside 24 hrs - ID Verde", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 91
 testRunner.Given("User is on the ReportFlyTip Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 92
 testRunner.When("they select No to first time report & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.And("they enter the case number of the previous case & select next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 94
 testRunner.When("they confirm yes to case details & click on next", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 95
 testRunner.Then("they get a confirmation case number & escalate email sent to ID Verde", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
